name: Build and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PYTHON_BIN: $HOME/.local/bin
      PIPENV_DEV: true
      PIPENV_SEQUENTIAL: true

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dev dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pipenv
        pipenv install --deploy --dev
    - name: Lint with flake8
      run: |
        pipenv run flake8 $GITHUB_WORKSPACE --count --statistics
      continue-on-error: true
    - name: Check import orders with isort
      run: |
        pipenv run isort -c -q
      continue-on-error: true
    - name: Test with pytest
      run: |
        pipenv run pytest $GITHUB_WORKSPACE
      continue-on-error: true
    - name: Collect coverage results
      run: |
        pipenv run coverage report -m --fail-under 85
      continue-on-error: true
