name: Build and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PYTHON_BIN: $HOME/.local/bin
      PIPENV_DEV: true
      PIPENV_SEQUENTIAL: true

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dev dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pipenv
        pipenv install --deploy --dev
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pipenv run flake8 $GITHUB_WORKSPACE --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        pipenv run flake8 $GITHUB_WORKSPACE --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Check import orders with isort
      run: |
        pipenv run isort -c -q
    - name: Test with pytest
      run: |
        pipenv run pytest
    - name: Collect coverage results
      run: |
        pipenv run coverage report -m --fail-under 85
