name: Build and Test

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - '.github/workflows/**'
      - 'Pipfile*'

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SODIUM_INSTALL: system

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dev dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pipenv
        sudo apt-get update
        sudo apt-get install -y libsodium-dev
        pipenv install --deploy --dev
    - name: Lint with flake8
      run: |
        pipenv run flake8 $GITHUB_WORKSPACE --count --statistics
      continue-on-error: true
    - name: Check import orders with isort
      run: |
        pipenv run isort -c -q
      continue-on-error: true
    - name: Check for type errors with mypy
      run: |
        mypy $GITHUB_WORKSPACE/src/age
    - name: Test with pytest
      run: |
        pipenv run pytest $GITHUB_WORKSPACE
    - name: Collect coverage results
      run: |
        pipenv run coverage report -m --fail-under 50
      continue-on-error: true
