name: Build and Test

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/**'
      - 'Pipfile*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8']

    name: Python ${{ matrix.python-version }} - Build and Test

    steps:
    - uses: actions/checkout@master

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pyage
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pipenv
        pipenv install --deploy --dev

    - name: Lint with flake8
      run: |
        pipenv run flake8 $GITHUB_WORKSPACE --count --statistics

    - name: Check import orders with isort
      run: |
        pipenv run isort -c -q

    - name: Check for type errors with mypy
      run: |
        pipenv run mypy $GITHUB_WORKSPACE/src/age

    - name: Test with pytest
      run: |
        pipenv run pytest $GITHUB_WORKSPACE

    - name: Collect coverage results
      run: |
        pipenv run coverage report -m --fail-under 50
      continue-on-error: true
