name: Compatibility with FiloSottile/age

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - '.github/workflows/**'
      - 'Pipfile*'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Install age
      run: |
        cd $HOME
        git clone https://filippo.io/age
        cd age
        go build -o . filippo.io/age/cmd/...

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install pyage
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pipenv
        pipenv install --deploy --dev

    - name: "Sanity check: age -> age"
      run: |
        export KEYFILE=$GITHUB_WORKSPACE/testdata/key.txt
        export PUBKEY=age1m2pjpe8zmldysvpp2esn7jw87m7ywk3lncslfwv07vu8wkht438szyhngp
        echo "Hello Golang sanity." | $HOME/age/age -r $PUBKEY | $HOME/age/age -d -i $KEYFILE

    - name: "Sanity check: pyage -> pyage"
      run: |
        export KEYFILE=$GITHUB_WORKSPACE/testdata/key.txt
        export PUBKEY=age1m2pjpe8zmldysvpp2esn7jw87m7ywk3lncslfwv07vu8wkht438szyhngp
        echo "Hello Python sanity." | pipenv run pyage encrypt $PUBKEY | pipenv run pyage decrypt $KEYFILE

    - name: age -> pyage
      run: |
        export KEYFILE=$GITHUB_WORKSPACE/testdata/key.txt
        export PUBKEY=age1m2pjpe8zmldysvpp2esn7jw87m7ywk3lncslfwv07vu8wkht438szyhngp
        echo "Hello pyage." | $HOME/age/age -r $PUBKEY | pipenv run pyage decrypt $KEYFILE

    - name: pyage -> age
      run: |
        export KEYFILE=$GITHUB_WORKSPACE/testdata/key.txt
        export PUBKEY=age1m2pjpe8zmldysvpp2esn7jw87m7ywk3lncslfwv07vu8wkht438szyhngp
        echo "Hello (go)age." | pipenv run pyage encrypt $PUBKEY | $HOME/age/age -d -i $KEYFILE

    - name: Install SSH-RSA keys
      run: |
        mkdir -p $HOME/.ssh
        cp $GITHUB_WORKSPACE/testdata/test_rsa.pub $HOME/.ssh/id_rsa.pub
        cp $GITHUB_WORKSPACE/testdata/test_rsa $HOME/.ssh/id_rsa

    - name: "SSH-RSA: age -> pyage"
      run: |
        echo "Hello pyage SSH." | $HOME/age/age -r "$(<$HOME/.ssh/id_rsa.pub)" | pipenv run pyage decrypt

    - name: "SSH-RSA: pyage -> age"
      run: |
        echo "Hello (go)age SSH." | pipenv run pyage encrypt $HOME/.ssh/id_rsa.pub | $HOME/age/age -d -i $HOME/.ssh/id_rsa
