name: Publish to TestPyPI

on:
  # push:
  #   branches:
  #     - master
  workflow_dispatch:

jobs:
  publish-testpypi:
    name: Build and publish pyage to TestPyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install pyage
        run: |
          cd $GITHUB_WORKSPACE
          pip install wheel
          pip install -e .

      - name: Build a binary wheel and a source tarball
        run: |
          python setup.py sdist bdist_wheel --dist-dir dist/

      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/
