name: Publish to PyPI and TestPyPI

on: push

jobs:
  build-n-publish:
    name: Build and publish pyage to PyPI and TestPyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install pyage
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pipenv
          pipenv install --deploy --dev

      - name: Build a binary wheel and a source tarball
        run: |
          pipenv run python setup.py sdist bdist_wheel --dist-dir dist/

      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/
